---
# tasks file for roles/k8s_clear
- name: clear k8s cluster
  shell: "kubeadm reset -f"
  failed_when: false
  when: inventory_hostname in groups['k8s_master'][0]


- name: delete cni directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/etcd
    - /etc/cni/net.d

- name: clear iptables rules
  iptables:
    flush: yes

- name: getting iptables calico chain
  shell: "iptables -nL|grep Chain|grep cali|awk '{print $2}'"
  register: iptables_chain

- name: clean iptables calico chain
  shell: "iptables -X {{ item }}"
  with_items:
    - "{{ iptables_chain.stdout_lines }}"

- name: getting iptables docker chain
  shell: "iptables -nL|grep Chain|grep DOCKER|awk '{print $2}'"
  register: iptables_docker_chain

- name: clean iptables docker chain
  shell: "iptables -X {{ item }}"
  with_items:
    - "{{ iptables_docker_chain.stdout_lines }}"

- name: getting iptables kube chain
  shell: "iptables -nL|grep Chain|grep KUBE|awk '{print $2}'"
  register: iptables_docker_chain

- name: clean iptables kube chain
  shell: "iptables -X {{ item }}"
  with_items:
    - "{{ iptables_docker_chain.stdout_lines }}"

- name: save iptables rules
  shell: "service iptables save"
  failed_when: false

- name: remove k8s images
  shell: "docker rmi {{ image_repository }}/{{ item }}:{{ kubernetes_version }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy

- name: remove package
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - docker-ce
