---
# tasks file for roles/k8s
- include: bootstrap.yml

- block:
    - name: debug init command
      debug:
        msg: "kubeadm init --kubernetes-version={{ kubernetes_version }}  --pod-network-cidr={{ pod_cidr }}  --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}  --ignore-preflight-errors=Swap  --image-repository {{ image_repository }} --log-file /var/log/kubernetes"

    - name: init k8s cluster
      shell: "kubeadm init --kubernetes-version={{ kubernetes_version }}  --pod-network-cidr={{ pod_cidr }}  --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}  --ignore-preflight-errors=Swap  --image-repository {{ image_repository }} --log-file /var/log/kubernetes"
      failed_when: false

    - name: create kube directory
      file:
        path: /root/.kube
        state: directory

    - name: create kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config

    - name: create calico pod for k8s cluster
      k8s:
        state: present
        src: "/opt/{{ k8s_network_plugin }}.yaml"
  delegate_to: localhost
