---
- include: bootstrap.yml

- name: upgrade k8s cluster
  shell: "kubeadm upgrade apply {{ kubernetes_version }} -y"
  when: inventory_hostname in groups['k8s-master']

- name: upgrade k8s node
  shell: "kubeadm upgrade node"
  when: inventory_hostname in groups['k8s-master'][0]

- name: restart kubelet service
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: create calico pod for k8s cluster
  k8s:
    state: present
    src: "/opt/{{ k8s_network_plugin }}.yaml"
