---

- name: install containerd
  yum:
    name: containerd.io
    state: present

- name: create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: configure containerd
  shell: "containerd config default > /etc/containerd/config.toml"

- name: get pause image version
  ansible.builtin.shell: cat /etc/containerd/config.toml | grep -o 'pause:[^"]*'
  register: pause_version

- name: debug pause version
  debug:
    msg: "{{ pause_version.stdout }}"

- name: modify containerd registry
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '    sandbox_image = '
    line: '    sandbox_image = "{{ image_repository }}/{{ pause_version.stdout }}"'
  notify: restart containerd service
    
  
- name: start containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started

- name: create crictl config file
  copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml
