---

- name: install containerd
  yum:
    name: containerd.io
    state: present

- name: create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: configure containerd
  shell: "containerd config default > /etc/containerd/config.toml"
  
- name: start containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started
