---
- name: install docker-ce 
  yum:
    name: docker-ce
    state: present

- name: create docker directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: copy daemon.json for docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker service

- name: started docker service
  systemd:
    name: docker
    state: started
    enabled: yes

