---
# tasks file for roles/init-os
- include: os.yaml

- include: yum.yaml

- include: lvm.yml
  tags: lvm

- name: debug ansible version
  debug:
    msg: "{{ ansible_version.full }}"

- include: docker.yml
  #when: kubernetes_version is version_compare('v1.23.0', '<')
  when: container_engine == 'docker'

- include: containerd.yml
  #when: kubernetes_version is version_compare('v1.23.0', '<=')
  when: container_engine == 'containerd'
