---
- name: find repo files
  find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
  register: repo_files

- name: delete yum files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ repo_files.files }}" 

- name: copy docker yum file
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - "{{ arch[ansible_architecture]['base']}}"
    - "epel.repo"
    - "docker-ce.repo"
    - "kubernetes.repo"
    
- name: install software
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_pkg }}"

- name: copy chrony config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: startup chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Install kernel package
  yum:
    name: kernel-3.10.0-1160.83.1.el7
    state: latest
  when: enable_kernel_upgrade | bool
  notify: Reboot server
