---
# defaults file for roles/init-os
vgdocker_name: 'vgdocker'
vgdata_name: 'vgdata'
vgpg_name: 'vgpg'
lvdocker_name: '{{ 99999 | random }}'
lvdata_name: '{{ 99999 | random }}'
lvpg_name: '{{ 99999 | random }}'
install_pkg:
  - lvm2
  - telnet
  - expect
  - rsync
  - nc
  - nfs-utils
  - python-docker-py
  - python-devel
  - mariadb-devel
  - MySQL-python
  - mariadb
  - docker-ce-18.09.9-3.el7
  - chrony

vg:
  docker:
    name: 'vgdocker'
    group: 'vgdocker'
    lv_name: '{{ 99999 | random }}'
  data:
    name: 'vgdata'
    group: 'vgdata'
    lv_name: '{{ 99999 | random }}'
  pg:
    name: 'vgpg'
    group: 'vgpg'
    lv_name: '{{ 99999 | random }}'

chrony_server: "{{ deploy_node_ip }}"
arch:
  x86_64:
    base: 'CentOS-Base.repo'
  arm64:
    base: 'CentOS-altarch-7.repo'
